name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize, closed]
    branches:
      - main
      - dev

permissions:
  contents: write
  pages: write
  id-token: write
  pull-requests: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Install and Build 🏗️
        if: github.event.action != 'closed'
        run: |
          npm install
          npm run build

      # This manages the 'pr-preview/' folder on the 'gh-pages' branch
      - name: Deploy PR Preview 🚀
        if: github.event_name == 'pull_request'
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./dist
          preview-branch: gh-pages
          umbrella-dir: pr-preview

      # This puts the main site into the root of the 'gh-pages' branch
      - name: Deploy Production to gh-pages 🌐
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
          clean: false # CRITICAL: Prevents deleting the 'pr-preview' folder
